language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - pip install -r requirements/develop.pip codecov
script:
  - inv qa cover --report
after_success:
  - codecov --file=reports/coverage.xml
