language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - pip install -e .[test,qa,doc,dev] python-coveralls
script:
  - inv cover qa
after_success:
  - coveralls -c coverage.rc
