language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - pypy
  - pypy3
install:
  - poetry install
  - poetry run pip install codecov
script:
  - poetry run inv qa cover --report
after_success:
  - poetry run codecov --file=reports/coverage.xml
